[user]
pseudo = "dred"
initial = "D"
counter = 2

[preferences]
language = "fr"
palette = "bleu"
dark_mode = true

[preferences.weekly_schedule]
slots = [
    [
    "deep",
    "deep",
    "deep",
    "deep",
    "deep",
    "deep",
    "deep",
    "deep",
    "none",
    "none",
    "light",
    "light",
    "light",
    "light",
    "none",
    "none",
    "routine",
    "routine",
    "routine",
    "routine",
    "none",
    "none",
    "none",
    "none",
],
    [
    "deep",
    "deep",
    "deep",
    "deep",
    "deep",
    "deep",
    "deep",
    "deep",
    "none",
    "none",
    "light",
    "light",
    "light",
    "light",
    "none",
    "none",
    "routine",
    "routine",
    "routine",
    "routine",
    "none",
    "none",
    "none",
    "none",
],
    [
    "deep",
    "deep",
    "deep",
    "deep",
    "deep",
    "deep",
    "deep",
    "deep",
    "none",
    "none",
    "light",
    "light",
    "light",
    "light",
    "none",
    "none",
    "routine",
    "routine",
    "routine",
    "routine",
    "none",
    "none",
    "none",
    "none",
],
    [
    "deep",
    "deep",
    "deep",
    "deep",
    "deep",
    "deep",
    "deep",
    "deep",
    "none",
    "none",
    "light",
    "light",
    "light",
    "light",
    "none",
    "none",
    "routine",
    "routine",
    "routine",
    "routine",
    "none",
    "none",
    "none",
    "none",
],
    [
    "deep",
    "deep",
    "deep",
    "deep",
    "deep",
    "deep",
    "deep",
    "deep",
    "none",
    "none",
    "light",
    "light",
    "light",
    "light",
    "none",
    "none",
    "routine",
    "routine",
    "routine",
    "routine",
    "none",
    "none",
    "none",
    "none",
],
    [
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
],
    [
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
],
]
